"""one

Revision ID: df286a21314e
Revises: e73ec946a653
Create Date: 2021-11-22 21:47:50.542069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df286a21314e'
down_revision = 'e73ec946a653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statusCustom',
    sa.Column('statusCustom', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('statusCustom')
    )
    op.create_table('statusProduct',
    sa.Column('statusProduct', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('statusProduct')
    )
    op.drop_table('statusproduct')
    op.drop_table('statuscustom')
    op.drop_constraint('custom_ibfk_1', 'custom', type_='foreignkey')
    op.drop_constraint('custom_ibfk_2', 'custom', type_='foreignkey')
    op.create_foreign_key(None, 'custom', 'production', ['productionid'], ['idproduct'])
    op.create_foreign_key(None, 'custom', 'statusCustom', ['statusCustomid'], ['statusCustom'])
    op.add_column('production', sa.Column('idproduct', sa.Integer(), nullable=False))
    op.drop_constraint('production_ibfk_1', 'production', type_='foreignkey')
    op.create_foreign_key(None, 'production', 'statusProduct', ['statusProductid'], ['statusProduct'])
    op.drop_column('production', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'production', type_='foreignkey')
    op.create_foreign_key('production_ibfk_1', 'production', 'statusproduct', ['statusProductid'], ['statusProduct'])
    op.drop_column('production', 'idproduct')
    op.drop_constraint(None, 'custom', type_='foreignkey')
    op.drop_constraint(None, 'custom', type_='foreignkey')
    op.create_foreign_key('custom_ibfk_2', 'custom', 'statuscustom', ['statusCustomid'], ['statusCustom'])
    op.create_foreign_key('custom_ibfk_1', 'custom', 'production', ['productionid'], ['id'])
    op.create_table('statuscustom',
    sa.Column('statusCustom', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('statusCustom'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('statusproduct',
    sa.Column('statusProduct', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('statusProduct'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('statusProduct')
    op.drop_table('statusCustom')
    # ### end Alembic commands ###
