"""one

Revision ID: e73ec946a653
Revises: 
Create Date: 2021-11-22 18:54:19.368727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73ec946a653'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statusCustom',
    sa.Column('statusCustom', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('statusCustom')
    )
    op.create_table('statusProduct',
    sa.Column('statusProduct', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('statusProduct')
    )
    op.create_table('user',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=20), nullable=False),
    sa.Column('firstName', sa.String(length=20), nullable=False),
    sa.Column('lastName', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('userStatus', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('statusProductid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['statusProductid'], ['statusProduct.statusProduct'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipDate', sa.DateTime(), nullable=False),
    sa.Column('packed', sa.Boolean(), nullable=True),
    sa.Column('statusCustomid', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('productionid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['productionid'], ['production.id'], ),
    sa.ForeignKeyConstraint(['statusCustomid'], ['statusCustom.statusCustom'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.Id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom')
    op.drop_table('production')
    op.drop_table('user')
    op.drop_table('statusProduct')
    op.drop_table('statusCustom')
    # ### end Alembic commands ###
